default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: goodscout
  password: goodscout1102

development:
  <<: *default
  host: 153.120.82.113
  database: goodscout_development

test:
  <<: *default
  host: 153.120.82.113
  database: goodscout_test

staging:
  <<: *default
  socket: /var/run/mysqld/mysqld.sock
  database: goodscout_staging

production:
  <<: *default
  socket: /var/run/mysqld/mysqld.sock
  database: goodscout
