default: &default
  adapter: mysql2
  host: 153.120.82.113
  encoding: utf8
  pool: 5
  username: goodscout
  password: goodscout1102

development:
  <<: *default
  database: goodscout_development

test:
  <<: *default
  database: goodscout_test

staging:
  <<: *default
  database: goodscout_staging

production:
  <<: *default
  database: goodscout
